spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db # PostgreSQL URL, mydatabase를 실제 데이터베이스 이름으로 변경
    username: root # PostgreSQL 사용자 이름
    password: 1234 # PostgreSQL 사용자 비밀번호
    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성 (운영 환경에서는 'none' 또는 'validate' 추천)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Hibernate dialect
        format_sql: true # SQL을 보기 쉽게 출력

  # H2 Console 비활성화
#  h2:
#    console:
#      enabled: false

openai:
  secret-key: ${OPENAI_SECRET_KEY}
  organization-id: ${OPENAI_ORGANIZATION_ID}



#spring :
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql:true
#
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#
#
#
#openai:
#  secret-key: ${OPENAI_SECRET_KEY}
#  organization-id: ${OPENAI_ORGANIZATION_ID}
#
#
#
