
openai:
  secret-key: ${OPENAI_SECRET_KEY}
  organization-id: ${OPENAI_ORGANIZATION_ID}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create # 테이블 자동 생성 (운영 환경에서는 'none' 또는 'validate' 추천)
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Hibernate dialect
        format_sql: true # SQL을 보기 쉽게 출력


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:5173/login/oauth"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.jdbc: debug

jwt:
  access-expiration-time: 86400000
  refresh-expiration-time: 2592000000
  secret-key: ${JWT_SECRET_KEY}

naver:
  api:
    client-id: ${NAVER_API_CLIENTID}
    secret-key: ${NAVER_API_SECRETKEY}

file:
  upload-dir: /Users/iseohyeon/capstone/uploads/




