on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Java 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Gradle Wrapper에 실행 권한 추가
    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./gradlew

    # Gradle로 JAR 파일 빌드
    - name: Build Application
      run: ./gradlew clean build

    # Docker Hub 로그인
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    # Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      run: |
        docker build -t naaadang876/newreals:latest .
        docker push naaadang876/newreals:latest
        
    # Docker Compose로 애플리케이션 배포
    - name: Deploy Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/newreals-app
          docker-compose pull app # 앱 컨테이너만 최신 이미지로 업데이트
          docker-compose up -d --no-deps app # 데이터베이스는 유지하고 앱만 재시작
          docker ps
