name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Save private key to file
        run: |
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key_path: ~/.ssh/id_rsa
          script: |
            echo "Testing SSH connection..."
            whoami
          debug: true

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key_path: ~/.ssh/id_rsa
          script: |
            echo "Deploying application..."
            cd /home/ubuntu/newreals-app
            docker-compose down || true
            docker-compose up -d
          debug: true

      - name: Debug SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_HOST }} -v


