on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Gradle로 JAR 파일 빌드
    - name: Build Application
      run: |
        ./gradlew clean build

    # 서버로 JAR 파일 업로드 및 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # EC2 서버의 작업 디렉터리로 이동
          cd /home/ubuntu/newreals-app
          
          # 기존 컨테이너 중지
          docker-compose down || true
          
          # 새로운 JAR 파일 업로드
          scp build/libs/newReals_BE.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/newreals-app/app.jar
          
          # Docker Compose로 애플리케이션 재배포
          docker-compose build
          docker-compose up --build -d


